baseURL: "https://github.com/lowkeyjoe/lowkeyjoe.github.io" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: FREEJOE
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

# languages:
#     en:
# languageName: "Chinese"
weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
    main:
        - name: 搜索
          url: search/
          weight: 10
        - name: 归档
          url: archives/
          weight: 5
        - name: 标签
          url: tags/
          weight: 10
        - name: 关于
          url: about/
        # - name: Discord
        #   url: https://discord.gg/ahpmTvhVmp

    # fr:
    #     languageName: ":fr:"
    #     languageAltTitle: French
    #     weight: 2
    #     title: PaperModL2
    #     taxonomies:
    #       category: FRcategories
    #       tag: FRtags
    #       series: FRseries
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
    #         imageTitle: ProfileMode image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Profile Mode
    #               url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: FRTags
    #               url: frtags
    #               weight: 10
    #             - name: FRCategories
    #               url: frcategories
    #               weight: 10
    #             - name: FRSeries
    #               url: frseries
    #               weight: 10
    #             - name: NullLink
    #               url: "#"

    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     taxonomies:
    #       category: FAcategories
    #       tag: FAtags
    #       series: FAseries
    #     menu:
    #         main:
    #             - name: FATags
    #               url: fatags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "freejoe's site"
    author: freejoe
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    DateFormat: "2006-01-02"  # 日期格式化
    ShowFullTextinRSS: true   # RSS 输出全文

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "FREEJOE'S HOME"
        Content: >
              , 这里记录我的学习笔记, 教程和随笔

    socialIcons:
        - name: github
          url: "https://github.com/lowkeyjoe"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/lowkeyjoe/lowkeyjoe.github.io/content"
        Text: "修改建议" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]



markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

# privacy:
#     vimeo:
#         disabled: false
#         simple: true

#     twitter:
#         disabled: false
#         enableDNT: true
#         simple: true

#     instagram:
#         disabled: false
#         simple: true

#     youtube:
#         disabled: false
#         privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true